version: "0.2"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd appCourse
      - echo "Installing dependencies"
      - npm ci
  build:
    commands:
      - echo "Starting compilation"
      - npm run build --project appCDev --configuration=production
  post_build:
    commands:
      - aws s3 rm s3://curso-angulargroup16 --recursive
      - aws s3 sync dist/app-cdev/browser s3://curso-angulargroup16 --delete
      - aws cloudfront create-invalidation --distribution-id E1SPEJ75714I63 --paths '/*'
artifacts:
  name: "Angular 16"
  files:
    - "**/*"
  base-directory: "dist/app-cdev/browser"
